version: 2
project_name: nrdot-collector-releases
release:
  draft: true
  use_existing_draft: true
  disable: "true"
msi:
  - id: nrdot-collector
    name: nrdot-collector
    wxs: ./windows/installer.wxs
    extra_files:
      - config.yaml
builds:
  - id: nrdot-collector
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    dir: _build
    binary: nrdot-collector
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=
    overrides:
      - goos: linux
        goarch: amd64
        flags:
          - -trimpath
          - -buildmode=pie
      - goos: linux
        goarch: arm64
        flags:
          - -trimpath
          - -buildmode=pie
archives:
  - id: nrdot-collector
    builds:
      - nrdot-collector
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - src: config.yaml
nfpms:
  - file_name_template: '{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{- if not (eq (filter .ConventionalFileName "\\.rpm$") "") }}{{- replace .Arch "amd64" "x86_64" }}{{- else }}{{- .Arch }}{{- end }}{{- with .Arm }}v{{ . }}{{- end }}{{- with .Mips }}_{{ . }}{{- end }}{{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{- end }}'
    package_name: nrdot-collector
    contents:
      - src: nrdot-collector.service
        dst: /lib/systemd/system/nrdot-collector.service
      - src: nrdot-collector.conf
        dst: /etc/nrdot-collector/nrdot-collector.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/nrdot-collector/config.yaml
        type: config
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    rpm:
      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'
    deb:
      signature:
        key_file: '{{ .Env.GPG_KEY_PATH }}'
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    id: nrdot-collector
    builds:
      - nrdot-collector
    formats:
      - deb
      - rpm
    maintainer: New Relic <otelcomm-team@newrelic.com>
    description: NRDOT Collector - nrdot-collector
    license: Apache 2.0
snapshot:
  version_template: '{{ incpatch .Version }}-SNAPSHOT-{{.ShortCommit}}'
checksum:
  name_template: '{{ .ArtifactName }}.sum'
  algorithm: sha256
  split: true
blobs:
  - bucket: nr-releases
    provider: s3
    region: us-east-1
    directory: nrdot-collector-releases/nrdot-collector/{{ .Version }}/{{ .ShortCommit }}
changelog:
  disable: "true"
signs:
  - args:
      - --batch
      - -u
      - '{{ .Env.GPG_FINGERPRINT }}'
      - --output
      - ${signature}
      - --detach-sign
      - --armor
      - ${artifact}
    signature: ${artifact}.asc
    artifacts: all
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:latest-amd64'
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --build-arg=DIST_NAME=nrdot-collector
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-arm64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:latest-arm64'
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --build-arg=DIST_NAME=nrdot-collector
    use: buildx
docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:{{ .Version }}-arm64'
  - name_template: '{{ .Env.REGISTRY }}/nrdot-collector:latest'
    image_templates:
      - '{{ .Env.REGISTRY }}/nrdot-collector:latest-amd64'
      - '{{ .Env.REGISTRY }}/nrdot-collector:latest-arm64'
